# Generated by Django 3.2.5 on 2022-04-07 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('id', models.UUIDField(default=uuid.UUID('36e2318f-b202-4f07-a447-a96c32c88a81'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
